import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/ui/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full w-full flex flex-col pb-[62px]">
<div className="max-w-5xl mx-auto relative min-h-screen bg-neutral-bg">
          
          {/* Content ของแต่ละหน้า */}
          <main className="">
            {children}
          </main>
        <button
          className="absolute top-[24px] right-[26px] z-50 p-2 cursor-pointer"
          aria-label="Close"
        >
          <img
            src="/closeButton.svg"
            className="w-[11.33px] h-[11.33px]"
            alt="Close"
          />
          </button>
          </div>
        <NavBar />
      </body>
    </html>
  );
}
